server:
  type: simple
  applicationContextPath: /
  rootPath: /api/*
  connector:
    type: http
    port: ${PORT}

logging:
  level: INFO

  loggers:
    com.heroku.kafka.demo: DEBUG

kafka:
  topic: ${KAFKA_PREFIX}${KAFKA_TOPIC}
  consumerGroup: ${KAFKA_PREFIX}${KAFKA_CONSUMERGRP}